define({
  addDistance: "添加距离单位",
  addArea: "添加面积单位",
  label: "标签",
  abbr: "缩写",
  conversion: "转换",
  actions: "行为",
	areaUnits: "面积单位",
  distanceUnits: "距离单位",
  kilometers: '公里',
  miles: '英里',
  meters: '米',
  feet: '英尺',
  yards: '码',
  squareKilometers: '平方公里',
  squareMiles: '平方英里',
  acres: '英亩',
  hectares: '公顷',
  squareMeters: '平方米',
  squareFeet: '平方英尺',
  squareYards: '平方码'
});