define({
  root: {
    selectDrawMode: "Select drawing mode",
    clear: "Clear",
    point: "Point",
    line: "Line",
    polyline: "Polyline",
    freehandPolyline: "Freehand Polyline",
    triangle: "Triangle",
    extent: "Extent",
    circle: "Circle",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Freehand Polygon",
    text:"Text",
    style:"Style",
    alpha:"Alpha",
    width:"Width",
    size:"Size",
    color:"Color",
    markerColor:"Marker Color",
    outlineColor:"Outline Color",
    lineColor:"Line Color",
    fillColor:"Fill Color",
    showMeasurements:"Show Measurements",
    areaUnits:"Area Units",
    distanceUnits:"Distance Units",
    kilometers:'Kilometers',
    miles:'Miles',
    meters:'Meters',
    feet:'Feet',
    yards:'Yards',
    squareKilometers:'Square kilometers',
    squareMiles:'Square miles',
    acres:'Acres',
    hectares:'Hectares',
    squareMeters:'Square meters',
    squareFeet:'Square feet',
    squareYards:'Square yards'
  },
  "zh-cn": true
});